config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "static_pages#home"
  resources :users
  resources :chats
  resources :messages
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :sender, class_name: "User", foreign_key: :user_id
    belongs_to :chat

    before_validation :normalize

    validates :user_id, presence: true
    validates :chat_id, presence: true
    validates :chat, presence: true
    validates :body, presence: true
    validate :valid_sender

    def normalize
        self.body = body.strip
    end

    def valid_sender
        return if chat.nil? || user_id.nil?

        if user_id != chat.sender_id
            errors.add(:user_id, "must match the chat's sender_id")
        end
    end

    def receiver
        return chat.receiver_id
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

    before_action :set_message, only: [:show, :edit, :update, :destroy]
    before_action :set_users, only: [:new, :create, :edit, :update]
    before_action :set_chats, only: [:new, :create, :edit, :update]
    before_action :authenticate_user!, only:[:new, :edit, :show, :index]

    load_and_authorize_resource

    def index
        @messages = Message.all
    end

    def show
        @user = @message.sender
        @chat = @message.chat
    end

    def new
        @message = Message.new
    end

    def create
        @message = Message.new message_params

        if @message.save
            redirect_to messages_path
        else
            render :new
        end
    end

    def edit
    end

    def update
        if @message.update message_params
            redirect_to messages_path
        else
            render :edit
        end
    end

    def destroy
        @message.destroy
        redirect_to messages_path
    end

    private
    def set_message
        @message = Message.find(params["id"])
    end

    def set_users
        @users = User.all
    end

    def set_chats
        @chats = Chat.all
    end

    def message_params
        params.require(:message).permit(:chat_id, :user_id, :body)
    end
end

app/views/messages/_form.html.erb
<div class="container justify-content-center">
    <%= form_with model: @message do |form| %>
        <div class="d-flex justify-content-between">
            <h2 class="">Create Messages</h2>
            <%= form.submit "Save", class: "btn btn-outline-dark mt-2 mb-2" %>
        </div>
        <table class="table w-100" style="table-layout: fixed;">
            <tr>
                <th></th>
                <th>ID: </th>
                <th>Chat ID: </th>
                <th>User ID: </th>
                <th>Body: </th>
                <th>Created At: </th>
                <th>Updated At: </th>
                <th></th>
            </tr>
            <tr>
                <td></td>
                <td><%= @message.id %></td>
                <td><%= form.collection_select :chat_id, @chats, :id, :id %></td>
                <td><%= form.collection_select :user_id, @users, :id, :first_name %></td>
                <td><%= form.text_field :body, class: "form-control" %></td>
                <td><%= @message.created_at %></td>
                <td><%= @message.updated_at %></td>
                <td></td>
            </tr>
        </table>
        <% if @message.errors.any? %>
            <h5>Error</h5>
            <ul>
                <% @message.errors.full_messages.each do |err| %>
                    <li><%= err %></li>
                <% end %>
            </ul>
        <% end %>
    <% end %>
</div>

app/views/messages/_nav.html.erb
<header class="d-flex justify-content-center">
    <nav class="navbar navbar-expand-lg ">
    <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="nav-link" href="/users">Users</a>
            <a class="nav-link" href="/messages">Messages</a>
            <a class="nav-link" href="/chats">Chats</a>
        </div>
        </div>
    </div>
    </nav>
</header>

app/views/messages/edit.html.erb
<%= render "form" %>

app/views/messages/index.html.erb
<div class="table-responsive container justify-content-center">
    <div class="d-flex justify-content-between">
        <h3 class="">Messages</h2>
        <a class="btn btn-outline-dark mt-2 mb-2"href="/messages/new">Add</a>
    </div>
    <table class="table w-100" style="table-layout: fixed;">
        <tr>
            <th></th>
            <th>ID: </th>
            <th>Chat ID: </th>
            <th>User ID: </th>
            <th>Body: </th>
            <th>Created At: </th>
            <th>Updated At: </th>
            <th></th>
        </tr>
        <% @messages.each do |message| %>
            <tr>
                <% if can? :show, message %>
                    <td><%= link_to("Show", message_path(message), class: "btn btn-outline-dark") %></td>
                <% else %>
                    <td></td>
                <% end %>

                <td><%= message.id %></td>
                <td><%= message.chat_id %></td>
                <td><%= message.user_id %></td>

                <% if can? :show, message %>
                    <td><%= message.body %></td>
                <% else %>
                    <td><p class="text-muted">Content Hidden</p></td>
                <% end %>

                <td><%= message.created_at %></td>
                <td><%= message.updated_at %></td>

                <% if can? :edit, message %>
                    <td><%= link_to("Edit", edit_message_path(message), class: "btn btn-outline-dark") %></td>
                <% else %>
                    <td></td>
                <% end %>
            </tr>
        <% end %>
</table>

app/views/messages/new.html.erb
<%= render "form" %>

app/views/messages/show.html.erb
<div class="table-responsive container justify-content-center">
    <div class="d-flex justify-content-between">
        <h3 class="">Message</h3>
        <a class="btn btn-outline-dark mt-2 mb-2"href="/messages/new">Add</a>
    </div>
    <table class="table w-100" style="table-layout: fixed;">
        <tr>
            <th></th>
            <th>ID: </th>
            <th>Chat ID: </th>
            <th>User ID: </th>
            <th>Body: </th>
            <th>Created At: </th>
            <th>Updated At: </th>
            <th></th>
        </tr>
        <tr>
            <% if can? :destroy, @message %>
                <td><%= button_to "Delete", message_path(@message), method: :delete, data: { confirm: "Delete message?" }, class: "btn btn-outline-dark" %></td>
            <% else %>
                <td></td>
            <% end %>
            <td><%= @message.id %></td>
            <td><%= @message.chat_id %></td>
            <td><%= @message.user_id %></td>
            <td><%= @message.body %></td>
            <td><%= @message.created_at %></td>
            <td><%= @message.updated_at %></td>

            <% if can? :edit, @message %>
                <td><%= link_to("Edit", edit_message_path(@message), class: "btn btn-outline-dark") %></td>
            <% else %>
                <td></td>
            <% end %>
        </tr>
    </table>

    <div class = "mt-5 "><h3>Sender</h3></div>

    <table class="table w-100" style="table-layout: fixed;">
        <tr>
            <th class = "mx-5"></th>
            <th>ID: </th>
            <th>First Name: </th>
            <th>Last Name: </th>
            <th>Email: </th>
            <th>Created At: </th>
            <th>Updated At: </th>
            <th></th>
        </tr>
        <tr>
            <td><%= link_to("Show", user_path(@user), class: "btn btn-outline-dark") %></td>
            <td><%= @user.id %></td>
            <td><%= @user.first_name %></td>
            <td><%= @user.last_name %></td>
            <td><%= @user.email %></td>
            <td><%= @user.created_at %></td>
            <td><%= @user.updated_at %></td>

            <% if can? :edit, @user %>
                <td><%= link_to("Edit", edit_user_registration_path(@user), class: "btn btn-outline-dark") %></td>
            <% else %>
                <td></td>
            <% end %>
        </tr>
    </table>

    <div class = "mt-5 "><h3>Chat</h3></div>

    <table class="table w-100" style="table-layout: fixed;">
        <tr>
            <th></th>
            <th>ID: </th>
            <th>Sender ID: </th>
            <th>Receiver ID: </th>
            <th>Created At: </th>
            <th>Updated At: </th>
            <th></th>
        </tr>
        <tr>
            <% if can? :show, @chat %>
                <td><%= link_to("Show", chat_path(@chat), class: "btn btn-outline-dark") %></td>
            <% else %>
                <td></td>
            <% end %>
            
            <td><%= @chat.id %></td>
            <td><%= @chat.sender_id %> <span class="text-muted">(<%= @chat.sender.first_name %>)</span></td>
            <td><%= @chat.receiver_id %> <span class="text-muted">(<%= @chat.receiver.first_name %>)</span></td>
            <td><%= @chat.created_at %></td>
            <td><%= @chat.updated_at %></td>

            <% if can? :edit, @chat %>
                <td><%= link_to("Edit", edit_chat_path(@chat), class: "btn btn-outline-dark") %></td>
            <% else %>
                <td></td>
            <% end %>
        </tr>
    </table>
</div>